words = [
    "makuta pompeluca",
    "salayumacoma en la... coma?",
    "potato",
    "chimichanga",
    "oompaloompa",
    "banana",
    "spaghet",
    "kerfuffle",
    "yeet",
    "platypus",
    "alacumbra",
    "flibbertigibbet",
    "shenanigans",
    "bamboozled",
    "hippopotamus",
    "wubba lubba dub dub",
    "ay caramba",
    "omelette du fromage",
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "supercalifragilisticexpialidocious",
    "bazinga",
    "llanfairpwllgwyngyll",
    "broccoli supremacy",
    "the mitochondria is the powerhouse of the cell",
    "chmod 777 everything",
    "sudo make me a sandwich",
    "frankly my dear, I don't give a SIGTERM",
    "Error 418: I'm a teapot",
    "there's no place like 127.0.0.1",
    "this is fine",
    "hold my beer",
    "insert coin to continue",
    "avocado toast",
    "the cake is a lie",
    "mango",
    "segfault in real life",
    "ctrl+z my life choices",
    "powered by coffee and regret",
    "404 motivation not found",
    "plot twist",
]
