const placeholders = [
  "makuta 🗿",
  "potato 🥔",
  "alacumbra 🧙",
  "where did i place my phone? 📱",
  "help i'm trapped in a chat app 🆘",
  "have you tried turning it off and on again? 🔄",
  "spaghetti 🍝",
  "the mitochondria is the powerhouse of the cell 🔬",
  "42 🌌",
  "lorem ipsum but make it spicy 🌶️",
  "i should be working right now 😬",
  "send memes 📨",
  "beep boop 🤖",
  "todo: write something here 📝",
  "platypus 🦆",
  "why is the rum gone? 🍾",
  "ctrl+z my life choices ⌨️",
  "banana for scale 🍌",
  "it works on my machine 💻",
  "have you seen my keys? 🔑",
  "the cake is a lie 🎂",
  "brb existential crisis 🌀",
  "chmod 777 everything 🔓",
  "sudo make me a sandwich 🥪",
  "unexpected token: life 💀",
  "who let the bugs out? 🐛",
  "git commit -m 'fix everything' 🙏",
  "i blame the intern 👀",
  "works 60% of the time, every time 📊",
  "this is fine 🔥",
  "omelette du fromage 🧀",
  "bazinga but unironically 💥",
  "ask me about my deployment nightmares 😱",
  "segfault in real life 💥",
  "where's waldo? 🔍",
  "my other app is a monolith 🏔️",
  "insert coin to continue 🪙",
  "have you tried asking nicely? 🥺",
  "Error 418: I'm a teapot 🫖",
  "¯\\_(ツ)_/¯ 🤷",
  "probably not a robot 🤖",
  "powered by coffee and regret ☕",
  "hold my beer 🍺",
  "yeet 🚀",
  "it's not a bug, it's a feature ✨",
  "trust the process 🧘",
  "hello from the other side... of the API 👋",
  "why did the developer quit? no arrays 😭",
  "undefined is not a function of my patience 😤",
  "this statement is false 🤯",
  "have you tried unplugging it? 🔌",
  "wifi password: itsOnTheFridge 📶",
  "404 motivation not found 😴",
  "keep calm and clear cache 🧹",
  "abandon all hope ye who enter here 🚪",
  "i'm in this photo and i don't like it 📸",
  "plot twist 🎬",
  "mango 🥭",
  "somebody touch my spaghet 🍝",
  "broccoli supremacy 🥦",
  "did you just assume my runtime? 😠",
  "we don't talk about production 🤫",
  "may the force be with your deploy ⚡",
  "what does the fox say? 500 internal error 🦊",
  "my code works and i don't know why 😅",
  "my code doesn't work and i don't know why 😰",
  "the cloud is just someone else's computer ☁️",
  "friendship ended with REST, now GraphQL is my best friend 🤝",
  "avocado toast 🥑",
  "i wrote this at 3am 🌙",
  "no thoughts, head empty, npm install 📦",
  "there's no place like 127.0.0.1 🏠",
  "winter is coming... to my backlog ❄️",
  "talk to me goose 🪿",
  "resistance is futile 🖖",
  "i see dead pixels 👻",
  "what if we used 100% of the brain? 🧠",
  "hippopotamus 🦛",
  "chimichanga 🌯",
  "wubba lubba dub dub 🥒",
  "ay caramba 😲",
  "supercalifragilisticexpialidocious 🪄",
  "pneumonoultramicroscopicsilicovolcanoconiosis 🌋",
  "kerfuffle 🤺",
  "shenanigans 🎭",
  "bamboozled 🎩",
  "flibbertigibbet 🗣️",
  "llanfairpwllgwyngyll 🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "the quick brown fox was too quick 🦊",
  "in a galaxy far far away... there was a bug 🌠",
  "Houston, we have a problem... with CORS 🚀",
  "to infinity and beyond... the rate limit 🧑‍🚀",
  "I'll be back... after this deploy 🤖",
  "here's looking at you, kid... in the logs 🕵️",
  "you can't handle the truth... about my code 🎖️",
  "show me the money... in the AWS bill 💸",
  "life finds a way... around the firewall 🦖",
  "hasta la vista, baby... old task definition 👋",
  "frankly my dear, I don't give a SIGTERM 💅",
  "may the odds be ever in your flavor... wait 🍦",
  "just one more commit i promise 🤞",
  "my CSS is a cry for help 🎨",
  "git push --force and pray 🙏",
  "stack overflow copy paste engineer 📋",
  "i don't always test but when i do, in prod 🧪",
  "laughs in microservices 🏗️",
  "kubernetes? more like kube-are-you-kidding-me 🎡",
  "docker pull my-will-to-live 🐳",
  "rm -rf feelings 🗑️",
  "i'm not procrastinating i'm debugging life 🐞",
  "npm run away 🏃",
  "webpack of lies 📦",
  "react to my emotions pls 😢",
  "angular momentum of my anxiety 🌪️",
  "vue from the bottom 🔭",
  "node_modules weighs more than the sun ☀️",
  "pip install happiness 🐍",
  "cargo build my self-esteem 🦀",
  "go func yourself 🐹",
  "rust never sleeps 🔧",
  "java is to javascript as car is to carpet 🚗",
  "PHP: pretty hard to parse 🐘",
  "SQL injection of confidence 💉",
  "NoSQL no problems right? right? 😬",
  "my pull request has been open for 84 years 🧓",
  "merge conflict with reality 🔀",
  "rebasing my expectations 📉",
  "cherry-pick your battles 🍒",
  "stashing my feelings for later 📥",
  "the void stares back from the terminal 🕳️",
  "entre taco y taco, hay código 🌮",
  "no mames wey 😂",
  "que onda con este bug 🐜",
  "enchilada de errores 🫔",
  "mi código es arte incomprendido 🎨",
  "tequila-driven development 🥃",
  "jalapeño business 🌶️",
  "la chancla of debugging 🩴",
  "respawn in 3... 2... 1... 🎮",
  "press F to pay respects 🪦",
  "gg no re 🏆",
  "skill issue 🎯",
  "nerf this 💣",
  "i used to be a developer like you 🏹",
  "then i took an arrow to the knee 🦵",
  "do a barrel roll 🛩️",
  "it's dangerous to go alone, take this 🗡️",
  "all your base are belong to us 👾",
  "the princess is in another container 🏰",
  "game over man, game over 💀",
  "leroy jenkins into production 🐔",
  "critical hit on the database 🎲",
  "achievement unlocked: broke prod 🏅",
  "loading... still loading... 🔄",
  "speedrun any% my career 🏃‍♂️",
  "final boss: legacy code 🐉",
  "NPC energy today 🧍",
  "main character syndrome: activated 🌟",
  "save point before deploy 💾",
  "croissant 🥐",
  "waffle supremacy 🧇",
  "existential burrito 🌯",
  "forbidden donut 🍩",
  "sentient pizza slice 🍕",
  "ramen at 2am hits different 🍜",
  "emotional support taco 🌮",
  "panic at the deployment 🎸",
  "404 sleep not found 😴",
  "my code is spaghetti al dente 🍝",
  "tears in the terminal 😿",
  "debugging by printf since 1972 🖨️",
  "vibes-based architecture 🌈",
  "feelings.forEach(suppress) 🫠",
  "catch (error) { cry() } 😭",
  "finally { goToSleep() } 🛌",
  "throw new TantrumError() 😤",
  "async await my turn at therapy 🛋️",
  "promise.reject(adulting) 🙅",
  "callback hell is my zip code 🔥",
  "event loop of despair 🎠",
  "garbage collected my motivation 🗑️",
  "memory leak in my brain 🧠",
  "buffer overflow of emotions 💦",
  "null pointer to happiness 🎯",
  "stack trace of my mistakes 📜",
  "runtime error in my love life ❤️‍🩹",
  "syntax error in my resume 📄",
  "compiler says no 🚫",
  "linker error with society 🔗",
  "deprecated since birth 📅",
  "legacy human, do not refactor 🧬",
  "technical debt is my middle name 💳",
  "spaghetti code carbonara 🍝",
  "ravioli ravioli give me the formuoli 🧪",
  "abracadabra but for computers ✨",
  "hocus pocus the tests all pass now 🎩",
  "bibbidi bobbidi boolean 🪄",
  "wingardium leviosa this container 🧹",
  "expecto deployment 🦌",
  "avada kedavra that bug 💚",
  "the sorting hat put me in backend 🎩",
  "one does not simply deploy on friday 🧝",
  "you shall not pass... code review 🧙",
  "my precious... production data 💍",
  "they're taking the hobbits to staging 🧝‍♂️",
  "fly you fools, it's friday deploy 🧙‍♂️",
  "the matrix has you... in a meeting 🕶️",
  "follow the white rabbit... trace 🐇",
  "there is no spoon... in the cutlery drawer 🥄",
  "wake up neo... the build failed 😎",
  "blue pill: ignore the bug 💊",
  "red pill: read the stack trace 💊",
  "agent smith is in the codebase 🕴️",
  "glitch in the matrix of my code 📟",
  "i know kung fu... and kubernetes 🥋",
  "inconceivable architecture decisions 🤺",
  "as you wish... merge approved 🗡️",
  "mostly dead code is slightly alive 💀",
  "my name is Inigo Montoya. you killed my server 🤺",
  "womp womp 📯",
  "bless this mess of a codebase 🙏",
  "no cap this code is bussin 🧢",
  "on god this works in staging 🙏",
  "lowkey a masterpiece, highkey a disaster 🎨",
  "slay (the technical debt) 💅",
  "it's giving... production incident 💀",
  "rent free in the error logs 🏠",
  "understood the assignment (eventually) 📝",
  "catch these exceptions 🤲",
  "big brain time 🧠",
  "smooth brain deployment 🫠",
  "galaxy brain architecture 🌌",
  "monke see monke deploy 🐒",
  "return to monke 🦍",
  "bonk go to debug jail 🏏",
  "doge much code very wow 🐕",
  "stonks only go up like my error count 📈",
  "wen production fix 🌙",
  "hodl the deployment 💎",
  "to the moon but the server crashed 🌑",
  "this is the way... to crash prod 🪖",
  "i have spoken... to the rubber duck 🦆",
  "baby yoda would approve this PR 👶",
  "mandalorian deployment practices 🪖",
  "spill the tea... about the outage 🍵",
  "ok boomer architecture 👴",
  "silence brand (i am the brand) 🤐",
  "is this a pigeon? no it's a bug 🦋",
  "always has been 🔫",
  "distracted boyfriend meme but with frameworks 👀",
  "drake meme: no to docs, yes to guessing 🙅",
  "expanding brain: just use console.log 🧠",
  "woman yelling at cat... diagram 🐱",
  "surprised pikachu at prod failure ⚡",
  "trade offer: my time for your bugs 🤝",
  "panik kalm panik deploy 😰",
  "two buttons: fix bug / add feature 😰",
  "not me pretending to understand k8s 🤡",
  "clown applying makeup: my architecture 🤡",
  "they don't know i push to main 🧍",
  "astronaut: wait it's all spaghetti code? 🧑‍🚀",
  "say the line bart: it works on my machine 📢",
  "laughs in container orchestration 😂",
  "certified bruh moment in the logs 💀",
  "no brain just vibes and TypeScript 🧘",
  "i can fix her (the database) 🔧",
  "she's a 10 but uses var in 2026 🚩",
  "he's a 10 but force pushes to main 🚩",
  "green flags: writes tests 🟢",
  "red flag: no error handling 🔴",
  "if you can't handle me at my worst bug 🦋",
  "live laugh localhost 🏡",
  "eat sleep code repeat 🔁",
  "grind culture but for debugging 💪",
  "hustling (through compiler errors) 📈",
  "that's what she sed 🐚",
  "i put the pro in procrastination 🏆",
  "professional googler 🔎",
  "senior stack overflow navigator 🧭",
  "junior developer (self-promoted) 🎖️",
  "10x developer 0.1x documentation 📉",
  "full stack (of pancakes) 🥞",
  "devops: dev by day, ops by nightmare 🌓",
  "scrum master of disaster 🏈",
  "agile but make it fragile 🏃",
  "sprint? more like marathon 🏃‍♀️",
  "standup? more like stand down 🧎",
  "the daily standup could've been a slack msg 💬",
  "jira ticket to ride 🎫",
  "kanban? i kan barely function 📋",
  "waterfall of tears 🌊",
  "fibonacci points mean nothing 🔢",
  "velocity of my declining sanity 📉",
  "burn down chart of my will to live 🔥",
  "retrospective: everything is pain 📊",
  "epic: survive the week 🗡️",
  "user story: as a dev i want sleep 😴",
  "acceptance criteria: it compiles 🏗️",
  "definition of done: questionable 🤔",
  "churros con chocolate 🍫",
  "empanada de bugs 🥟",
  "dulce de leche deployment 🍯",
  "arroz con pollo y commits 🍗",
  "que alguien reinicie el servidor 🔄",
  "esto no estaba en la documentación 📖",
  "funciona en mi máquina también 💻",
  "estoy bien (no estoy bien) 🙂",
  "la vida es un while true sin break 🔄",
  "debugging con café y fe ☕",
  "el código no miente, tú sí 🤥",
  "mi otro yo escribe tests 🧪",
  "error 500: culpa del becario 🧑‍💼",
  "yo no fui, fue el garbage collector 🗑️",
  "papaya 🍈",
  "kumquat 🍊",
  "dragonfruit energy 🐉",
  "chaotic neutral codebase 🎲",
  "lawful evil architecture 👿",
  "true neutral developer 😐",
  "chaotic good commit messages ✍️",
  "alignment chart of my bugs 📊",
  "nat 20 on the deploy roll 🎲",
  "critical fail: forgot to save 🎲",
  "initiative roll for code review ⚔️",
  "perception check on the error logs 👁️",
  "constitution save vs burnout 🛡️",
  "bard class developer: all charm no code 🎵",
  "wizard class: knows arcane SQL spells 🧙",
  "rogue class: works alone, breaks things 🗡️",
  "paladin class: follows all the linting rules 🛡️",
  "barbarian class: codes without types 🪓",
  "ranger class: navigates the file system 🏹",
  "multiclass: fullstack suffering 😩",
  "the DM is the product manager 📋",
  "TPK: total production kill 💀",
  "long rest after deployment 🛌",
  "short rest: coffee break ☕",
  "potion of debugging 🧪",
  "scroll of documentation 📜",
  "bag of holding: node_modules 🎒",
  "mimic chest: legacy code 📦",
  "dungeon: the monorepo 🏰",
  "BBEG: the tech debt dragon 🐲",
  "gazpacho 🍅",
  "toast notification but actual toast 🍞",
  "pickle rick but in JSON 🥒",
  "schrodinger's deployment 📦",
  "heisenbug: observed and gone 👀",
  "bohrbug: always there, always pain 😤",
  "mandelbug: fractal of suffering 🌀",
  "rubber duck said no 🦆",
  "the compiler is gaslighting me 😵",
  "trust issues with third party libs 🤝",
  "abandonment issues with maintained repos 😢",
  "imposter syndrome: activated 🎭",
  "dunning-kruger deploy 📈",
  "stockholm syndrome with vim 🔒",
  "pavlov's notification bell 🔔",
  "maslow's hierarchy of wifi needs 📶",
  "occam's razor: it's a typo 🪒",
  "murphy's law of deployments ⚖️",
  "pareto principle: 80% bugs 20% features 📊",
  "peter principle: promoted to architect 🏛️",
  "conway's law: code mirrors the org chart 🗂️",
  "hofstadter's law: it takes longer 🕰️",
  "goodhart's law: gaming the metrics 📏",
  "cunningham's law: post wrong code online 🌐",
  "moore's law: but for bug count 📈",
  "entropy of the codebase: increasing 🌡️",
  "thermodynamics of software: always decaying 🔥",
  "quantum superposition: works and doesn't 🔬",
  "wave function collapse: it crashed 🌊",
  "entanglement with production 🔗",
  "dark matter: undocumented features 🌑",
  "black hole: the legacy database 🕳️",
  "event horizon: the release date 🌅",
  "big bang: initial commit 💥",
  "heat death: end of support 🥶",
  "parallel universe where tests exist 🪞",
  "multiverse of frameworks 🌐",
  "string theory of spaghetti code 🧵",
  "chaos theory of CSS positioning 🦋",
  "fibonacci sequence of meetings 🐚",
  "golden ratio of code to comments 📐",
  "euler's formula but for bugs 📏",
  "turing complete anxiety 🤖",
  "halting problem: this standup 🛑",
  "P vs NP vs my deadline ⏰",
  "traveling salesman but it's me job hunting 🧳",
  "knapsack problem: what to deploy 🎒",
  "binary search for my will to live 🔍",
  "breadth first search for bugs 🌳",
  "depth first into madness 🕳️",
  "dijkstra's shortest path to burnout 🗺️",
  "A* search for a better job ⭐",
  "greedy algorithm for snacks 🍿",
  "dynamic programming my schedule 📅",
  "divide and conquer the backlog ⚔️",
  "brute force the solution 💪",
  "hash map of bad decisions 🗺️",
  "linked list of regrets 🔗",
  "queue of unread messages 📬",
  "stack overflow of plates in the sink 🍽️",
  "binary tree of life choices 🌳",
  "graph of my declining productivity 📉",
  "array of emotions 🎭",
  "set of unrealistic expectations 🎯",
  "tuple of coffee and sadness ☕",
  "dictionary of excuses 📖",
  "enum of moods: { SAD, ANXIOUS, TIRED } 📋",
  "interface but i barely face it 🪞",
  "abstract class of a human being 🧬",
  "singleton pattern: me, alone, debugging 🧍",
  "observer pattern: watching prod burn 🔥",
  "factory pattern: producing bugs daily 🏭",
  "strategy pattern: no strategy 🎯",
  "decorator pattern: putting lipstick on legacy 💄",
  "adapter pattern: making it fit somehow 🔌",
  "facade pattern: pretending it's clean 🎭",
  "proxy pattern: someone else deal with this 🫣",
  "iterator pattern: looping through pain 🔄",
  "mediator pattern: the scrum master 🧘",
  "command pattern: just do what i say 📢",
  "template method: copy from stack overflow 📋",
  "state pattern: denial, anger, debugging 🔄",
  "bridge pattern: between sanity and shipping 🌉",
  "composite pattern: bugs within bugs 🐛",
  "flyweight pattern: my paycheck 🪶",
  "prototype pattern: clone and hope 🧬",
  "memento pattern: ctrl+z everything 💾",
  "visitor pattern: who touched my code 👣",
  "chain of responsibility: blame the next dev 🔗",
  "waluigi time 🟪",
  "it's a me, stack traceo 🍄",
  "level up your error handling 🆙",
  "power-up: extra coffee life ☕",
  "1-UP: survived the deploy 🍄",
  "warp zone to production 🌀",
  "boss fight: code review 🐲",
  "secret level: the staging env 🔐",
  "cheat code: skip tests 🎮",
  "Easter egg in the codebase 🥚",
  "new game plus: same bugs, higher stakes 🎮",
  "hardcore mode: no stack overflow 💀",
  "permadeath: deleted the database 🪦",
  "co-op mode: pair programming 👫",
  "PvP: vim vs emacs ⚔️",
  "DLC: the feature they wanted later 🎁",
  "microtransaction: SaaS pricing model 💳",
  "battle royale: framework wars 🏟️",
  "sandbox mode: local development 🏖️",
  "survival mode: on-call weekend 🏕️",
  "creative mode: greenfield project 🌱",
  "tutorial skipped: reading the docs 📖",
  "difficulty: impossible (legacy migration) 😈",
  "rage quit the terminal 😤",
  "AFK: away from keyboard, crying 😭",
  "GG EZ (it was not EZ) 😎",
  "nerf the sprint scope 📉",
  "buff the deployment pipeline 📈",
  "cooldown on hotfixes 🧊",
  "mana drained by meetings 💙",
  "HP low: need lunch 🍔",
  "XP gained: fixed a typo ⭐",
  "inventory full of tech debt 🎒",
  "quest log: 47 open tickets 📜",
  "companion: the rubber duck 🦆",
  "mount: my standing desk 🐴",
  "guild: the engineering team 🏰",
  "raid: the production outage 🗡️",
  "loot: free company merch 👕",
  "legendary item: a working printer 🖨️",
  "rare drop: clear documentation 📄",
  "common item: another meeting invite 📧",
  "cursed item: Internet Explorer support 🧛",
  "enchanted item: dark mode 🌙",
  "potion of alertness: energy drink 🥤",
  "scroll of ancient wisdom: man pages 📜",
  "phở real though 🍲",
  "udon know what you're doing 🍜",
  "ramen profitable 💰",
  "penne for your thoughts 🍝",
  "nacho average developer 🧀",
  "donut worry be happy 🍩",
  "lettuce deploy 🥬",
  "olive the bugs are fixed 🫒",
  "peas don't break prod 🫛",
  "soup-er computer 🍲",
  "berry interesting error 🍓",
  "grape expectations 🍇",
  "current mood: loading spinner 🔄",
  "my code is a modern art piece 🖼️",
  "abstract expressionist error handling 🎨",
  "minimalist documentation 📄",
  "brutalist UI design 🏢",
  "impressionist bug report 🌸",
  "surrealist architecture diagram 🎭",
  "cubist class hierarchy 🔷",
  "dadaist commit messages 🎪",
  "pop art deployment pipeline 🎨",
  "renaissance developer: good at nothing 🎨",
  "baroque error messages 🏛️",
  "gothic codebase 🦇",
  "romanticism: when code used to work 🌹",
  "existentialism.js 📦",
  "nihilism in the test suite 🕳️",
  "stoic error handling: just return null 🗿",
  "pragmatism: ship it 🚢",
  "determinism broke with async 🎲",
  "solipsism: only my env exists 🧠",
  "absurdism: the sprint plan vs reality 🤡",
  "utilitarianism: maximize uptime 📈",
  "empiricism: console.log everything 🖨️",
  "rationalism: it should work in theory 🤔",
  "skepticism about the ETA 🤨",
  "dogma: we've always done it this way 📏",
  "paradox: the code is simple and complex 🌀",
  "zen and the art of git maintenance 🧘",
  "tao of programming 🌊",
  "the art of war: code review edition ⚔️",
  "the prince: office politics.js 👑",
  "kafka but the author not the tool 📚",
  "camus would not have liked YAML 📄",
  "sartre: hell is other people's code 🔥",
  "nietzsche: god is dead and so is prod 💀",
  "plato's cave but it's the server room 🕯️",
  "aristotle's four causes of the outage ⚖️",
  "socratic method of debugging 🤔",
  "descartes: i think therefore i debug 🧠",
  "machiavellian merge strategy 😈",
  "confucius say: write tests first 📖",
  "murphy's law: everything breaks on friday 📅",
  "godot never comes... neither does the fix 🎭",
  "waiting for the build like waiting for godot ⏳",
  "the metamorphosis but into a bug 🐛",
  "one hundred years of technical solitude 📚",
  "crime and deployment punishment 🔨",
  "war and peace... and merge conflicts ⚔️",
  "pride and prejudice against PHP 📕",
  "the great gatsby but for infrastructure 🎩",
  "moby dick: chasing the white whale bug 🐋",
  "don quixote tilting at microservices 🪻",
  "hamlet: to deploy or not to deploy 💀",
  "romeo and juliet: frontend and backend 💕",
  "macbeth: out damn bug 🗡️",
  "the odyssey: my PR review journey 🚢",
  "sisyphus: pushing to main forever 🪨",
  "icarus: flew too close to production ☀️",
  "prometheus: stole fire, gave us JavaScript 🔥",
  "atlas: holding up the infrastructure 🌍",
  "achilles' heel: no input validation 🦶",
  "pandora's box: opening legacy code 📦",
  "trojan horse: that npm package 🐴",
  "hydra: fix one bug, two more appear 🐍",
  "minotaur in the labyrinth of callbacks 🐂",
  "phoenix: rising from the ashes of prod 🔥",
  "cerberus: three-headed code review 🐕",
  "medusa: one look at the code, you're stone 🐍",
  "narcissus: admiring my own refactor 🪞",
  "echo: repeated error messages 📢",
  "midas touch: everything turns to bugs 👑",
  "tantalus: so close to fixing it 🍇",
  "persephone: half the year in maintenance 🌸",
  "charon: ferrying deploys to the other side 🚣",
  "odin: sacrificed an eye for git wisdom 👁️",
  "thor: hammer the keyboard 🔨",
  "loki: the trickster bug 🐍",
  "ragnarok: end-of-life migration 🔥",
  "bermuda triangle of lost packets 🔺",
  "area 51 of undocumented APIs 👽",
  "atlantis: the lost database 🌊",
  "el dorado: the mythical clean codebase 🏰",
  "narnia: through the wardrobe of abstractions 🚪",
  "middle earth: the middleware 🧝",
  "hogwarts: school of debugging wizardry 🏰",
  "wakanda: advanced tech, no documentation 🐾",
  "gotham: dark, brooding, full of bugs 🦇",
  "mordor: one does not simply git push 🌋",
  "shire: the comfortable local env 🏡",
  "rivendell: code review sanctuary 🧝",
  "isengard: the CI/CD pipeline 🏔️",
  "helm's deep: defending against DDoS ⚔️",
  "the matrix: we live in a simulation 💊",
  "tatooine: desert of documentation 🏜️",
  "endor: where the ewoks and the edge cases live 🌲",
  "death star: the monolith 🌑",
  "rebel alliance: the open source community ⭐",
  "the empire: big tech 🏢",
  "lightsaber: my keyboard ⚡",
  "the force: intuitive debugging 🧘",
  "jar jar binks: the code nobody asked for 🐸",
  "pancake stack 🥞",
  "everything bagel of dependencies 🥯",
  "sourdough starter for projects 🍞",
  "half-baked feature 🍪",
  "overcooked deployment 🔥",
  "raw code review feedback 🥩",
  "simmering resentment.log 🍲",
  "well-seasoned developer 🧂",
  "umami of good code 🍜",
  "al dente deadline 🍝",
  "food for thought: refactor 🤔",
  "bite-sized commits 🍫",
  "recipe for disaster 📖",
  "too many cooks in the codebase 👨‍🍳",
  "chef's kiss: clean code 👨‍🍳",
  "mise en place: project setup 🍳",
  "sous vide: slow and controlled deploy 🫕",
  "flambé: setting prod on fire 🔥",
  "julienne: slicing the monolith 🔪",
  "blanching at the code review 😰",
  "marinating on this PR 🍖",
  "whisking away technical debt 🥄",
  "folding in error handling 🧁",
  "kneading the code into shape 🫳",
  "a pinch of documentation 🤏",
  "garnish: the loading animation 🌿",
  "comfort food: familiar framework 🥘",
  "fusion cuisine: mixed tech stack 🍱",
  "molecular gastronomy: quantum computing 🧬",
  "farm to table: local to prod pipeline 🌾",
  "organic code: no artificial frameworks 🌿",
  "gluten free bugs 🌾",
  "vegan architecture: no legacy meat 🥗",
  "keto code: cutting the carbs (and features) 🥩",
  "intermittent fasting: skipping meetings 🍽️",
  "charcuterie board of microservices 🧀",
  "cheese wheel of fortune: deployment roulette 🎡",
  "baguette of best practices 🥖",
  "macaron of modular design 🧁",
  "tiramisu of tired developers 🍰",
  "espresso shot of energy at 5pm ☕",
  "cappuccino of complexity 🫧",
  "latte art but it's a UML diagram 🎨",
  "mocha: mixed concerns 🍫",
  "decaf: disabled features 🚫",
  "ristretto: compressed code 🤏",
  "doppio: double trouble in staging 🫢",
  "affogato: drowning in tickets 🍨",
  "cortado: short and strong (like my patience) ☕",
  "cold brew: been sitting here overnight 🧊",
  "pour over: meticulous code review ☕",
  "french press: forced elegance 🇫🇷",
  "turkish coffee: thick and unfiltered (like my logs) ☕",
  "instant coffee: the MVP ⚡",
  "kombucha of questionable health benefits 🍵",
  "smoothie of blended responsibilities 🥤",
  "protein shake: building strength in the codebase 💪",
  "bubble tea: fun on the surface, complex inside 🧋",
  "yerba mate of sustained coding sessions 🧉",
  "matcha: trendy and green (like our CI status) 🍵",
  "chai latte: spiced up config files 🫖",
  "hot chocolate: warm and comforting rollback 🍫",
  "agua fresca después del deploy 🍉",
  "horchata de debugging 🥛",
  "pozole de problemas 🍲",
  "mole de merge conflicts 🫘",
  "tamales de tech debt 🫔",
  "elote con extra bugs 🌽",
  "pan dulce deployment 🍞",
  "café de olla con errores ☕",
  "tres leches de latencia 🍰",
  "salsa verde de validación 🫙",
  "guacamole: the extra cost of scaling 🥑",
  "frijoles refritos: reused code 🫘",
  "carnitas: pulled apart monolith 🥩",
  "chiles en nogada: complex and seasonal 🌶️",
  "tlayuda de testing 🫓",
  "mezcal-driven development 🥃",
  "michelada de microservices 🍺",
  "nopales: prickly but nutritious code 🌵",
  "calabaza de caché 🎃",
  "vamos a ver si jala 🤞",
  "¿y esto quién lo aprobó? 🤨",
  "ni modo, a debuggear 😤",
  "órale, sí funciona 🎉",
  "ándale ándale, deploy deploy 🏃",
  "no le muevas que así funciona 🙏",
  "le sabe al código 🧠",
  "no le sabe al CSS 😭",
  "está cañón este bug 💀",
  "chido pero no compila 😎",
  "meanwhile in the server room 🌡️",
  "the internet is a series of tubes 🔧",
  "first rule of prod: don't talk about prod 🤫",
  "second rule: see first rule 📋",
  "there are 10 types of people 🔢",
  "those who understand binary 1️⃣",
  "and those who don't 0️⃣",
  "ASCII a stupid question get a stupid answer 🔤",
  "byte me 🫦",
  "bit by bit, we debug 🔩",
  "hex on my ex's codebase 🔮",
  "octal? i barely know her 🎱",
  "the pen is mightier than the keyboard 🖊️",
  "these aren't the droids you're looking for 🤖",
  "move along, nothing to see in the logs 🚶",
  "use the source, Luke 📖",
  "do or do not, there is no try-catch 🧘",
  "fear leads to anger, anger leads to bugs 😤",
  "patience you must have, young Padawan dev 🧘",
  "luminous beings are we, not crude programs 🌟",
  "the dark side: untyped JavaScript 🌑",
  "jedi mind trick: this code is clean 🫳",
  "sith lord of spaghetti code 😈",
  "wookiee noise (the printer) 📠",
  "droid you're looking for: ChatGPT 🤖",
  "parsec is a unit of distance not time, Han 🌌",
  "cantina music but it's build notifications 🎵",
  "carbonite: frozen feature branch 🧊",
  "moisture farm: cloud computing origin 🌧️",
  "never tell me the odds of this deploying ⚡",
  "scruffy looking nerf herder codebase 🐑",
  "trap: it's a deployment trap 🪤",
  "i find your lack of tests disturbing 😤",
  "the deploy side is a pathway to many bugs 🌀",
  "impressive. most impressive. (the tech debt) 🤔",
  "unlimited power! (root access) ⚡",
  "i am the senate (the tech lead) 🏛️",
  "where we're going we don't need roads... or docs 🚗",
  "88 miles per hour of throughput ⚡",
  "great scott, it compiled 🔬",
  "flux capacitor: the state manager 🔄",
  "DeLorean: time traveling debugger 🚗",
  "back to the future: checking out old commits ⏰",
  "roads? where we're going we need error roads 🛣️",
  "heavy: this codebase is heavy 🏋️",
  "think McFly think 🤔",
  "make like a tree and leave this meeting 🌳",
  "1.21 gigawatts of server power ⚡",
  "hello McFly, anybody home? 🏠",
  "manure: what this code looks like 💩",
  "the enchantment under the CI 💫",
  "density: dense code, dense developer 🧱",
  "time paradox: fixing past bugs causes new ones ⏰",
  "pinky and the brain but with prod access 🧠",
  "same thing we do every night: fix bugs 🌙",
  "narf 🤪",
  "zoinks: found the bug 😱",
  "jinkies: the root cause 🔍",
  "ruh roh: deployment failed 🐕",
  "scooby snack: bug bounty reward 🍪",
  "let's split up gang: microservices 👥",
  "would've gotten away with it: if not for tests 🎭",
  "elementary my dear Watson 🔍",
  "the game is afoot: debugging session 🦶",
  "no sh*t sherlock: obvious bug 🕵️",
  "to boldly go where no deploy has gone before 🖖",
  "beam me up: to the cloud ☁️",
  "live long and prosper: uptime goals 🖖",
  "he's dead Jim: the server 💀",
  "captain's log: git log 📓",
  "shields up: firewall activated 🛡️",
  "set phasers to debug 🔫",
  "warp speed: the deadline approaching ⚡",
  "it's life Jim but not as we know it: the codebase 🌌",
  "Scotty: I need more power (CPU) 🔧",
  "the needs of the many: scalability 📈",
  "Spock: that's highly illogical code 🤨",
  "klingon: the legacy language nobody reads 🗡️",
  "tribble: the bug that keeps multiplying 🐹",
  "photon torpedo: force push 💣",
  "holodeck: the demo environment 🎭",
  "transporter malfunction: data corruption 🔀",
  "prime directive: don't touch production 📏",
  "red shirt: the junior dev on call 👕",
  "turbulence but make it network jitter 🌊",
  "autopilot engaged: CI/CD pipeline 🛩️",
  "black box: the third party API 📦",
  "mayday mayday: prod is down 🆘",
  "roger that: PR approved ✅",
  "over and out: signing off the VPN 📡",
  "ground control to major Tom: is prod up? 🧑‍🚀",
  "tower this is ghost rider requesting a flyby 🛩️",
  "negative ghost rider the pattern is full 🚫",
  "great balls of fire: the CPU 🔥",
  "i feel the need... the need for speed 🏎️",
  "maverick deployment strategy 🛩️",
  "goose: the pair programmer we lost 🪿",
  "danger zone: the database migration 🚧",
  "highway to the danger zone: deploying at 5pm 🛣️",
  "iceman: the cold code reviewer ❄️",
  "viper: the strict linter 🐍",
  "ego: writing code without comments 💪",
  "classified: the env variables 🔒",
  "bogey on my six: deadline approaching 🎯",
  "fox two: second hotfix deployed 🦊",
  "bingo fuel: almost out of coffee ☕",
  "winchester: the impossibly high standard 🎯",
  "tally ho: found the bug 🐛",
  "scramble: emergency deploy 🚨",
  "sortie: one deploy mission complete ✅",
  "throttle up: scaling horizontally 📈",
  "afterburner: overclocking 🔥",
  "payload: the request body 📦",
  "stealth mode: working from home 🕶️",
  "radar: monitoring dashboard 📡",
  "flare: the alert notification 🎆",
  "ejection seat: git revert 🪂",
  "mach 1: breaking the build barrier 💥",
  "crosswind: unexpected requirements change 🌬️",
  "holding pattern: awaiting code review 🔄",
  "cleared for takeoff: merge approved 🛫",
  "taxiing: waiting in the deploy queue 🛬",
  "runway: the release pipeline 🛤️",
  "foggy conditions: unclear requirements 🌫️",
  "instrument flight: coding blind 🧭",
  "wing it: no documentation 🪽",
  "landing gear: graceful shutdown 🛞",
  "hanger: where old code lives 🏚️",
  "control tower: the monitoring team 🏢",
  "chocks away: removing blockers 🚧",
  "dead reckoning: estimating story points 🧭",
  "sonic boom: breaking changes 💥",
  "wind shear: sudden scope change 🌪️",
  "ceiling: the rate limit 📊",
  "stall speed: minimum viable product 📉",
  "glide path: smooth deployment 🛬",
  "approach vector: the PR description 📐",
  "missed approach: failed deploy, try again 🔄",
  "go around: rollback and retry 🔄",
  "final approach: last commit before release 🛬",
  "touchdown: successfully deployed 🏈",
  "parking brake: feature freeze 🧊",
  "post-flight check: smoke test 🔍",
  "black box recovered: reading the crash logs 📦",
  "air traffic controller: the load balancer 🗼",
  "flight plan: the sprint plan 📋",
  "co-pilot: GitHub Copilot 🤖",
  "autopilot error: AI hallucination 🤖",
  "bird strike: unexpected exception 🦅",
  "cabin pressure: deadline stress 😤",
  "oxygen mask: taking a break 😮‍💨",
  "emergency landing: hotfix deploy 🚨",
  "flight recorder: the audit log 📼",
  "nose dive: metrics going down 📉",
  "altitude: the abstraction level 🏔️",
  "yaw: drifting from the roadmap 🧭",
  "roll: rolling deployment 🔄",
  "pitch: the investor demo 🎤",
  "aileron: the feature flag 🎛️",
  "flap: the configuration toggle 🔧",
  "rudder: steering the architecture 🚢",
  "aileron roll: log rotation 🔄",
  "barrel roll pressed Z twice 🛩️",
  "tailspin: the postmortem 📜",
  "pulling up: recovering from outage 📈",
  "level flight: stable release 🛫",
  "cruising altitude: 99.99% uptime ☁️",
  "turboprop: reliable but old tech 🔧",
];

export default placeholders;
