const placeholders = [
  "makuta 🗿",
  "potato 🥔",
  "alacumbra 🧙",
  "where did i place my phone? 📱",
  "help i'm trapped in a chat app 🆘",
  "have you tried turning it off and on again? 🔄",
  "spaghetti 🍝",
  "the mitochondria is the powerhouse of the cell 🔬",
  "42 🌌",
  "lorem ipsum but make it spicy 🌶️",
  "i should be working right now 😬",
  "send memes 📨",
  "beep boop 🤖",
  "todo: write something here 📝",
  "platypus 🦆",
  "why is the rum gone? 🍾",
  "ctrl+z my life choices ⌨️",
  "banana for scale 🍌",
  "it works on my machine 💻",
  "have you seen my keys? 🔑",
  "the cake is a lie 🎂",
  "brb existential crisis 🌀",
  "chmod 777 everything 🔓",
  "sudo make me a sandwich 🥪",
  "unexpected token: life 💀",
  "who let the bugs out? 🐛",
  "git commit -m 'fix everything' 🙏",
  "i blame the intern 👀",
  "works 60% of the time, every time 📊",
  "this is fine 🔥",
  "omelette du fromage 🧀",
  "bazinga but unironically 💥",
  "ask me about my deployment nightmares 😱",
  "segfault in real life 💥",
  "where's waldo? 🔍",
  "my other app is a monolith 🏔️",
  "insert coin to continue 🪙",
  "have you tried asking nicely? 🥺",
  "Error 418: I'm a teapot 🫖",
  "¯\\_(ツ)_/¯ 🤷",
  "probably not a robot 🤖",
  "powered by coffee and regret ☕",
  "hold my beer 🍺",
  "yeet 🚀",
  "it's not a bug, it's a feature ✨",
  "trust the process 🧘",
  "hello from the other side... of the API 👋",
  "why did the developer quit? no arrays 😭",
  "undefined is not a function of my patience 😤",
  "this statement is false 🤯",
  "have you tried unplugging it? 🔌",
  "wifi password: itsOnTheFridge 📶",
  "404 motivation not found 😴",
  "keep calm and clear cache 🧹",
  "abandon all hope ye who enter here 🚪",
  "i'm in this photo and i don't like it 📸",
  "plot twist 🎬",
  "mango 🥭",
  "somebody touch my spaghet 🍝",
  "broccoli supremacy 🥦",
  "did you just assume my runtime? 😠",
  "we don't talk about production 🤫",
  "may the force be with your deploy ⚡",
  "what does the fox say? 500 internal error 🦊",
  "my code works and i don't know why 😅",
  "my code doesn't work and i don't know why 😰",
  "the cloud is just someone else's computer ☁️",
  "friendship ended with REST, now GraphQL is my best friend 🤝",
  "avocado toast 🥑",
  "i wrote this at 3am 🌙",
  "no thoughts, head empty, npm install 📦",
  "there's no place like 127.0.0.1 🏠",
  "winter is coming... to my backlog ❄️",
  "talk to me goose 🪿",
  "resistance is futile 🖖",
  "i see dead pixels 👻",
  "what if we used 100% of the brain? 🧠",
  "hippopotamus 🦛",
  "chimichanga 🌯",
  "wubba lubba dub dub 🥒",
  "ay caramba 😲",
  "supercalifragilisticexpialidocious 🪄",
  "pneumonoultramicroscopicsilicovolcanoconiosis 🌋",
  "kerfuffle 🤺",
  "shenanigans 🎭",
  "bamboozled 🎩",
  "flibbertigibbet 🗣️",
  "llanfairpwllgwyngyll 🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "the quick brown fox was too quick 🦊",
  "in a galaxy far far away... there was a bug 🌠",
  "Houston, we have a problem... with CORS 🚀",
  "to infinity and beyond... the rate limit 🧑‍🚀",
  "I'll be back... after this deploy 🤖",
  "here's looking at you, kid... in the logs 🕵️",
  "you can't handle the truth... about my code 🎖️",
  "show me the money... in the AWS bill 💸",
  "life finds a way... around the firewall 🦖",
  "hasta la vista, baby... old task definition 👋",
  "frankly my dear, I don't give a SIGTERM 💅",
  "may the odds be ever in your flavor... wait 🍦",
];

export default placeholders;
